### ISSUE TITLE
Endo status NA for plants with seed mass

### ISSUE THREAD

**Issue by texmiller** [mdonald/AGHY_Final#10]
This is a data issue and not a software issue, so maybe not the best use of github's "issues" but this may be a good place to track problems nonetheless. I was looking at sample sizes in different years and treatments, and I notices that there are 27 plants in 2014 for which we have seed mass but endo status is NA. This seems odd so i thought I would run it past you. Perhaps these are problem plants that we could not confidently assign status to? Not a big deal but since we have smaller sample sizes in 2014 I thought it might be worth checking on. Here are the sample sizes by group. 

2014	0	Add	31	
2014	0	Control	30	
2014	1	Add	33	
2014	1	Control	54	
2014	NA	Add	11	
2014	NA	Control	16	
2015	0	Add	73	
2015	0	Control	50	
2015	1	Add	85	
2015	1	Control	105

**Comment by mdonald** [comment]
Thanks for noting this - it is odd, since if we have seeds, we should have scored them. I'll look into it.

**Comment by mdonald** [comment]
Looking at the raw data we have notes for 19 of them. Examples of the notes: all seeds "empty", all seeds without cells, no seeds to score (?), no seeds in envelope, no seeds to score. So based on these notes, despite collecting infs and weighing seeds, it looks like for these individuals we **did not** score seeds, and therefore **do not have endo status**. Because we also applied endo scores forward and backward, and these individuals still do not have and endo.stat - this means that we did not score seeds from this individual at any other point, nor did we collect a tiller for immunoblot assay. 

Code to identify the problem individuals (notes are located in _scoring_notes_t_)
## looking into the issue of why there are plants for which we have seed masses but no endo scores

issues <- AGHY.demo.final %>% 
          filter(seed_mass_t >0 & is.na(endo.stat))

**Comment by texmiller** [comment]
OK, then we are fine to proceed. Thanks for checking on those. I think we can close this issue!
